// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dmobxproleaaowsfqlnq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRtb2J4cHJvbGVhYW93c2ZxbG5xIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkyNDczMzIsImV4cCI6MjA2NDgyMzMzMn0.7bYuPTdakbny2yIaqOpO0KmlqycIxuQCPP1E7tYKhHA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);